import { User, Business, BusinessMember, Subscription, Customer, Pooja, Booking } from "@/lib/types";

export const SEED_USER: User = {
  id: "u-ravi-iyer-01",
  googleId: "google-1092837465",
  email: "ravi.iyer@gmail.com",
  name: "Ravi Iyer",
  avatarUrl: "",
  mobile: "+919876543210",
  mobileVerified: true,
  role: "OWNER",
  referralCode: "VELVI-RAVI123",
  createdAt: "2026-08-01T08:00:00Z",
};

export const SEED_SUPER_ADMIN: User = {
  id: "u-super-admin-01",
  googleId: "google-admin-9999",
  email: "admin@velvi.app",
  name: "Velvi Admin",
  avatarUrl: "",
  mobile: "+919999999999",
  mobileVerified: true,
  role: "SUPER_ADMIN",
  referralCode: "VELVI-ADMIN",
  createdAt: "2026-01-01T00:00:00Z",
};

export const SEED_BUSINESS: Business = {
  id: "biz-venkateswara-01",
  ownerId: "u-ravi-iyer-01",
  name: "",
  serviceName: "Pooja • Homam • Seva",
  iyerName: "",
  logoUrl: "",
  phone: "+919876543210",
  whatsapp: "",
  address: "",
  showWatermark: true,
  createdAt: "2026-08-01T08:30:00Z",
};

export const SEED_SUBSCRIPTION: Subscription = {
  id: "sub-ravi-01",
  businessId: "biz-venkateswara-01",
  planName: "Velvi Pro",
  planCode: "VELVI_PRO",
  status: "ACTIVE",
  trialStart: "2026-08-01T08:30:00Z",
  trialEnd: "2026-08-31T08:30:00Z",
  currentPeriodStart: "2026-08-31T08:30:00Z",
  currentPeriodEnd: "2026-10-18T23:59:59Z",
  billingCycle: "MONTHLY",
  autoRenew: true,
  createdAt: "2026-08-01T08:30:00Z",
  updatedAt: "2026-08-31T08:30:00Z",
};

export const SEED_MEMBERS: BusinessMember[] = [
  {
    id: "m-ravi-01",
    businessId: "biz-venkateswara-01",
    userId: "u-ravi-iyer-01",
    name: "Ravi Iyer",
    mobile: "+919876543210",
    role: "OWNER",
    active: true,
    specialization: "Rig Veda • Ganapathi, Ayushya & Gruhapravesam",
    workingDays: "All days",
    workingHours: "06:00 - 20:00",
    bookingCount: 16,
    createdAt: "2026-08-01T08:30:00Z",
  },
  {
    id: "m-suresh-02",
    businessId: "biz-venkateswara-01",
    userId: "u-suresh-iyer-02",
    name: "Suresh Iyer",
    mobile: "+919876543211",
    role: "IYER",
    active: true,
    specialization: "Yajur Veda • Navagraha & Sudarshana Homam",
    workingDays: "All days",
    workingHours: "06:00 - 21:00",
    bookingCount: 12,
    createdAt: "2026-08-05T10:00:00Z",
  },
  {
    id: "m-kumar-03",
    businessId: "biz-venkateswara-01",
    userId: "u-kumar-iyer-03",
    name: "Kumar Iyer",
    mobile: "+919876543212",
    role: "IYER",
    active: true,
    specialization: "Sama Veda • Sathyanarayana Pooja & Seemantham",
    workingDays: "Mon-Sat",
    workingHours: "07:00 - 18:00",
    bookingCount: 10,
    createdAt: "2026-08-10T11:00:00Z",
  },
  {
    id: "m-venkatesh-04",
    businessId: "biz-venkateswara-01",
    userId: "u-venkatesh-04",
    name: "Venkatesh Iyer",
    mobile: "+919876543213",
    role: "IYER",
    active: true,
    specialization: "Mrityunjaya, Chandi & Lakshmi Homam",
    workingDays: "Weekends & Muhurtham days",
    workingHours: "06:00 - 14:00",
    bookingCount: 6,
    createdAt: "2026-08-15T09:00:00Z",
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: "c-ramesh-01",
    businessId: "biz-venkateswara-01",
    name: "Ramesh Kumar",
    mobile: "+919876543210",
    whatsapp: "+919876543210",
    address: "45, Gandhi Nagar, Namakkal",
    city: "Namakkal",
    notes: "Family devotee for 6 years • Kuladeivam: Sri Arthanareeswarar",
    createdAt: "2026-08-12T10:00:00Z",
  },
  {
    id: "c-lakshmi-02",
    businessId: "biz-venkateswara-01",
    name: "Lakshmi Narayanan",
    mobile: "+918765432109",
    whatsapp: "+918765432109",
    address: "18, Cross Cut Road, Coimbatore",
    city: "Coimbatore",
    notes: "Requires Tamil Panchangam muhurtham notes before fixing dates",
    createdAt: "2026-08-20T14:00:00Z",
  },
  {
    id: "c-meena-03",
    businessId: "biz-venkateswara-01",
    name: "Meena Sundaram",
    mobile: "+919032145678",
    whatsapp: "+919032145678",
    address: "7, Fairlands, Salem",
    city: "Salem",
    notes: "Regular Navaratri, Varalakshmi & Pournami Pooja bookings",
    createdAt: "2026-08-25T16:00:00Z",
  },
  {
    id: "c-suresh-04",
    businessId: "biz-venkateswara-01",
    name: "Suresh Subramanian",
    mobile: "+919871234567",
    whatsapp: "+919871234567",
    address: "22, Brough Road, Erode",
    city: "Erode",
    notes: "Gruhapravesam & Vastu Homam in new duplex villa",
    createdAt: "2026-09-01T11:00:00Z",
  },
  {
    id: "c-vignesh-05",
    businessId: "biz-venkateswara-01",
    name: "Vigneshwaran K",
    mobile: "+919443219876",
    whatsapp: "+919443219876",
    address: "9, Thillai Nagar, Trichy",
    city: "Trichy",
    notes: "Sudarshana & Mrityunjaya Homam devotee • Referred by Ramesh",
    createdAt: "2026-09-02T12:00:00Z",
  },
  {
    id: "c-anandhi-06",
    businessId: "biz-venkateswara-01",
    name: "Anandhi & Senthil Nathan",
    mobile: "+919840123456",
    whatsapp: "+919840123456",
    address: "14, North Mada Street, Mylapore, Chennai",
    city: "Chennai",
    notes: "Sashtiapthapoorthi (60th Kalyanam) celebration with 4 priests",
    createdAt: "2026-09-03T10:00:00Z",
  },
  {
    id: "c-balaji-07",
    businessId: "biz-venkateswara-01",
    name: "Dr. Balaji Raghavan",
    mobile: "+919443156789",
    whatsapp: "+919443156789",
    address: "52, KK Nagar, Madurai",
    city: "Madurai",
    notes: "Dhanvantri Homam & Sri Rudra Abhishekam for health & hospital",
    createdAt: "2026-09-04T15:00:00Z",
  },
  {
    id: "c-karthik-08",
    businessId: "biz-venkateswara-01",
    name: "Karthikeyan Ramaswamy",
    mobile: "+919789012345",
    whatsapp: "+919789012345",
    address: "88, High Ground, Tirunelveli",
    city: "Tirunelveli",
    notes: "Murugan Sashti Homam & Chandi Homam devotee",
    createdAt: "2026-09-05T11:30:00Z",
  },
  {
    id: "c-gowri-09",
    businessId: "biz-venkateswara-01",
    name: "Gowri Shankar",
    mobile: "+919842178901",
    whatsapp: "+919842178901",
    address: "31, South Main Street, Thanjavur",
    city: "Thanjavur",
    notes: "Maha Ganapathi Homam & Vivaha Lagnam consulting",
    createdAt: "2026-09-06T09:00:00Z",
  },
  {
    id: "c-jayanthi-10",
    businessId: "biz-venkateswara-01",
    name: "Jayanthi Natarajan",
    mobile: "+919442345678",
    whatsapp: "+919442345678",
    address: "12, Sannathi Street, Kanchipuram",
    city: "Kanchipuram",
    notes: "Sri Kamakshi Pooja, Lalitha Sahasranamam & Navavarna Pooja",
    createdAt: "2026-09-07T14:30:00Z",
  },
  {
    id: "c-soundar-11",
    businessId: "biz-venkateswara-01",
    name: "Soundararajan M",
    mobile: "+919894012345",
    whatsapp: "+919894012345",
    address: "74, Salai Road, Dindigul",
    city: "Dindigul",
    notes: "Maha Lakshmi Kubera Pooja for business expansion",
    createdAt: "2026-09-08T16:00:00Z",
  },
  {
    id: "c-revathi-12",
    businessId: "biz-venkateswara-01",
    name: "Revathi Krishnan",
    mobile: "+919790123456",
    whatsapp: "+919790123456",
    address: "25, Katpadi Road, Vellore",
    city: "Vellore",
    notes: "Ayushya Homam & Vidyarambham Aksharabhyasam for grandson",
    createdAt: "2026-09-09T10:00:00Z",
  },
];

export const SEED_POOJAS: Pooja[] = [
  {
    id: "p-ganapathi-01",
    businessId: "biz-venkateswara-01",
    englishName: "Ganapathi Homam",
    tamilName: "கணபதி ஹோமம்",
    description: "Invokes Lord Ganesha to remove all obstacles, grant success, health and prosperity before new ventures.",
    durationMinutes: 150,
    basePrice: 5000,
    procedure: "Sankalpam, Ganapathi Avahanam, Shodashopachara Pooja, 108 Ashtothram, Ganapathi Moola Mantra Homam, Poornahuthi, Aashirvadam.",
    active: true,
    items: [
      { id: "gi-1", poojaId: "p-ganapathi-01", itemEnglishName: "Turmeric Powder", itemTamilName: "மஞ்சள் தூள்", quantity: 100, unit: "g", sortOrder: 1 },
      { id: "gi-2", poojaId: "p-ganapathi-01", itemEnglishName: "Kumkum", itemTamilName: "குங்குமம்", quantity: 50, unit: "g", sortOrder: 2 },
      { id: "gi-3", poojaId: "p-ganapathi-01", itemEnglishName: "Betel Leaves", itemTamilName: "வெற்றிலை", quantity: 21, unit: "nos", sortOrder: 3 },
      { id: "gi-4", poojaId: "p-ganapathi-01", itemEnglishName: "Betel Nuts", itemTamilName: "பாக்கு", quantity: 21, unit: "nos", sortOrder: 4 },
      { id: "gi-5", poojaId: "p-ganapathi-01", itemEnglishName: "Banana", itemTamilName: "வாழைப்பழம்", quantity: 12, unit: "nos", sortOrder: 5 },
      { id: "gi-6", poojaId: "p-ganapathi-01", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 5, unit: "nos", sortOrder: 6 },
      { id: "gi-7", poojaId: "p-ganapathi-01", itemEnglishName: "Raw Rice", itemTamilName: "பச்சரிசி", quantity: 2, unit: "kg", sortOrder: 7 },
      { id: "gi-8", poojaId: "p-ganapathi-01", itemEnglishName: "Navadhanyam Set", itemTamilName: "நவதானியம்", quantity: 1, unit: "set", sortOrder: 8 },
      { id: "gi-9", poojaId: "p-ganapathi-01", itemEnglishName: "Samithu Bundle", itemTamilName: "சமித்துக் கட்டு", quantity: 1, unit: "bundle", sortOrder: 9 },
      { id: "gi-10", poojaId: "p-ganapathi-01", itemEnglishName: "Pure Cow Ghee", itemTamilName: "தூய பசு நெய்", quantity: 500, unit: "ml", sortOrder: 10 },
      { id: "gi-11", poojaId: "p-ganapathi-01", itemEnglishName: "Flowers & Garlands", itemTamilName: "பூ மாலை & உதிரிப்பூ", quantity: 500, unit: "g", sortOrder: 11 },
      { id: "gi-12", poojaId: "p-ganapathi-01", itemEnglishName: "Jaggery (Vellam)", itemTamilName: "வெல்லம்", quantity: 500, unit: "g", sortOrder: 12 },
      { id: "gi-13", poojaId: "p-ganapathi-01", itemEnglishName: "Dry Fruits & Nuts", itemTamilName: "உலர்ந்த திராட்சை & முந்திரி", quantity: 100, unit: "g", sortOrder: 13 },
      { id: "gi-14", poojaId: "p-ganapathi-01", itemEnglishName: "Modakam / Prasadam", itemTamilName: "மோதகம் நைவேத்தியம்", quantity: 21, unit: "nos", sortOrder: 14 },
    ],
    createdAt: "2026-08-01T09:00:00Z",
  },
  {
    id: "p-ayushya-02",
    businessId: "biz-venkateswara-01",
    englishName: "Ayushya Homam",
    tamilName: "ஆயுஷ்ய ஹோமம்",
    description: "Performed on birthdays or milestones to grant longevity, good health, and vitality for child or elder.",
    durationMinutes: 180,
    basePrice: 6000,
    active: true,
    items: [
      { id: "ai-1", poojaId: "p-ayushya-02", itemEnglishName: "Turmeric Powder", itemTamilName: "மஞ்சள் தூள்", quantity: 100, unit: "g", sortOrder: 1 },
      { id: "ai-2", poojaId: "p-ayushya-02", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 6, unit: "nos", sortOrder: 2 },
      { id: "ai-3", poojaId: "p-ayushya-02", itemEnglishName: "Pure Cow Ghee", itemTamilName: "பசு நெய்", quantity: 1, unit: "litre", sortOrder: 3 },
      { id: "ai-4", poojaId: "p-ayushya-02", itemEnglishName: "Samithu Bundle", itemTamilName: "சமித்துக் கட்டு", quantity: 2, unit: "bundle", sortOrder: 4 },
      { id: "ai-5", poojaId: "p-ayushya-02", itemEnglishName: "Charu Patram / Rice", itemTamilName: "சாரு நைவேத்திய பச்சரிசி", quantity: 2, unit: "kg", sortOrder: 5 },
      { id: "ai-6", poojaId: "p-ayushya-02", itemEnglishName: "Honey (Thaen)", itemTamilName: "சுத்தமான தேன்", quantity: 100, unit: "ml", sortOrder: 6 },
    ],
    createdAt: "2026-08-01T09:10:00Z",
  },
  {
    id: "p-navagraha-03",
    businessId: "biz-venkateswara-01",
    englishName: "Navagraha Homam",
    tamilName: "நவகிரக ஹோமம்",
    description: "Pacifies planetary doshas and brings peace, stability, family harmony, and planetary blessings.",
    durationMinutes: 180,
    basePrice: 7500,
    active: true,
    items: [
      { id: "ni-1", poojaId: "p-navagraha-03", itemEnglishName: "Navadhanyam Set", itemTamilName: "நவதானியம் 9 வகை", quantity: 1, unit: "set", sortOrder: 1 },
      { id: "ni-2", poojaId: "p-navagraha-03", itemEnglishName: "9 Color Vastram", itemTamilName: "9 வண்ண வஸ்திரம்", quantity: 1, unit: "set", sortOrder: 2 },
      { id: "ni-3", poojaId: "p-navagraha-03", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 9, unit: "nos", sortOrder: 3 },
      { id: "ni-4", poojaId: "p-navagraha-03", itemEnglishName: "Pure Cow Ghee", itemTamilName: "பசு நெய்", quantity: 1, unit: "litre", sortOrder: 4 },
      { id: "ni-5", poojaId: "p-navagraha-03", itemEnglishName: "Navagraha Samithu", itemTamilName: "நவகிரக சமித்து 9 வகை", quantity: 1, unit: "set", sortOrder: 5 },
    ],
    createdAt: "2026-08-01T09:20:00Z",
  },
  {
    id: "p-gruhapravesam-04",
    businessId: "biz-venkateswara-01",
    englishName: "Gruhapravesam & Vastu Homam",
    tamilName: "கிரகப்பிரவேசம் & வாஸ்து ஹோமம்",
    description: "Traditional new house-warming ceremony, Vastu Purusha, Ganapathi, Navagraha & Lakshmi Homam.",
    durationMinutes: 240,
    basePrice: 12000,
    active: true,
    items: [
      { id: "gi-101", poojaId: "p-gruhapravesam-04", itemEnglishName: "Gomatha Pooja Set", itemTamilName: "கோ பூஜை பொருட்கள்", quantity: 1, unit: "set", sortOrder: 1 },
      { id: "gi-102", poojaId: "p-gruhapravesam-04", itemEnglishName: "Fresh Milk & Pot", itemTamilName: "பால் காய்ச்சும் பாத்திரம் & பால்", quantity: 2, unit: "litre", sortOrder: 2 },
      { id: "gi-103", poojaId: "p-gruhapravesam-04", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 11, unit: "nos", sortOrder: 3 },
      { id: "gi-104", poojaId: "p-gruhapravesam-04", itemEnglishName: "Vastu Yantram & Moorthy", itemTamilName: "வாஸ்து எந்திரம்", quantity: 1, unit: "nos", sortOrder: 4 },
      { id: "gi-105", poojaId: "p-gruhapravesam-04", itemEnglishName: "Navaratnam Set", itemTamilName: "நவரத்தினம்", quantity: 1, unit: "set", sortOrder: 5 },
      { id: "gi-106", poojaId: "p-gruhapravesam-04", itemEnglishName: "Pancha Kavyam", itemTamilName: "பஞ்சகவ்யம்", quantity: 1, unit: "set", sortOrder: 6 },
    ],
    createdAt: "2026-08-01T09:30:00Z",
  },
  {
    id: "p-sathyanarayana-05",
    businessId: "biz-venkateswara-01",
    englishName: "Sathyanarayana Pooja",
    tamilName: "சத்தியநாராயண பூஜை",
    description: "Traditional auspicious Vratham for blessings, wish fulfillment, and family prosperity on Pournami.",
    durationMinutes: 120,
    basePrice: 4500,
    active: true,
    items: [
      { id: "si-1", poojaId: "p-sathyanarayana-05", itemEnglishName: "Sathyanarayana Photo/Idol", itemTamilName: "ஸ்ரீ சத்தியநாராயணர் படம்", quantity: 1, unit: "nos", sortOrder: 1 },
      { id: "si-2", poojaId: "p-sathyanarayana-05", itemEnglishName: "Sooji & Sugar for Sheera", itemTamilName: "ரவை & சர்க்கரை ஷீரா பிரசாதம்", quantity: 1, unit: "kg", sortOrder: 2 },
      { id: "si-3", poojaId: "p-sathyanarayana-05", itemEnglishName: "Tulasi Leaves", itemTamilName: "துளசி தளம்", quantity: 100, unit: "g", sortOrder: 3 },
      { id: "si-4", poojaId: "p-sathyanarayana-05", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 5, unit: "nos", sortOrder: 4 },
      { id: "si-5", poojaId: "p-sathyanarayana-05", itemEnglishName: "Dry Fruits for Prasad", itemTamilName: "உலர் திராட்சை முந்திரி", quantity: 100, unit: "g", sortOrder: 5 },
    ],
    createdAt: "2026-08-01T09:40:00Z",
  },
  {
    id: "p-sudarshana-06",
    businessId: "biz-venkateswara-01",
    englishName: "Sudarshana Homam",
    tamilName: "சுதர்சன ஹோமம்",
    description: "Invokes Lord Sudarshana Chakra for absolute protection from negative energy, enemies and evil eyes.",
    durationMinutes: 180,
    basePrice: 8500,
    active: true,
    items: [
      { id: "sui-1", poojaId: "p-sudarshana-06", itemEnglishName: "White Mustard Seeds", itemTamilName: "வெண்கடுகு", quantity: 250, unit: "g", sortOrder: 1 },
      { id: "sui-2", poojaId: "p-sudarshana-06", itemEnglishName: "Pure Cow Ghee", itemTamilName: "பசு நெய்", quantity: 1, unit: "litre", sortOrder: 2 },
      { id: "sui-3", poojaId: "p-sudarshana-06", itemEnglishName: "Red Silk Cloth", itemTamilName: "சிவப்பு பட்டு வஸ்திரம்", quantity: 1, unit: "nos", sortOrder: 3 },
    ],
    createdAt: "2026-08-01T09:50:00Z",
  },
  {
    id: "p-rudra-07",
    businessId: "biz-venkateswara-01",
    englishName: "Sri Rudra Ekadasa Homam",
    tamilName: "ஸ்ரீ ருத்ர ஏகாதச ஹோமம்",
    description: "Vedic Maha Rudrabhishekam with 11 anuvakams of Sri Rudram for health, spiritual elevation & peace.",
    durationMinutes: 210,
    basePrice: 9000,
    active: true,
    items: [
      { id: "ri-1", poojaId: "p-rudra-07", itemEnglishName: "Vibhuti (Sacred Ash)", itemTamilName: "திருநீறு / விபூதி", quantity: 200, unit: "g", sortOrder: 1 },
      { id: "ri-2", poojaId: "p-rudra-07", itemEnglishName: "Bilva Leaves", itemTamilName: "வில்வ இலை", quantity: 108, unit: "nos", sortOrder: 2 },
      { id: "ri-3", poojaId: "p-rudra-07", itemEnglishName: "Panchamirtham Set", itemTamilName: "பஞ்சாமிர்தம்", quantity: 1, unit: "set", sortOrder: 3 },
      { id: "ri-4", poojaId: "p-rudra-07", itemEnglishName: "Pure Ghee", itemTamilName: "பசு நெய்", quantity: 1, unit: "litre", sortOrder: 4 },
    ],
    createdAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "p-lakshmi-kubera-08",
    businessId: "biz-venkateswara-01",
    englishName: "Maha Lakshmi Kubera Pooja",
    tamilName: "மகா லக்ஷ்மி குபேர பூஜை",
    description: "Divine pooja invoking Goddess Lakshmi & Lord Kubera for wealth, debt relief and business success.",
    durationMinutes: 90,
    basePrice: 4500,
    active: true,
    items: [
      { id: "li-1", poojaId: "p-lakshmi-kubera-08", itemEnglishName: "Lotus Flowers", itemTamilName: "தாமரை மலர்கள்", quantity: 16, unit: "nos", sortOrder: 1 },
      { id: "li-2", poojaId: "p-lakshmi-kubera-08", itemEnglishName: "Kubera Coins / Yantram", itemTamilName: "குபேர நாணயங்கள் / எந்திரம்", quantity: 1, unit: "set", sortOrder: 2 },
      { id: "li-3", poojaId: "p-lakshmi-kubera-08", itemEnglishName: "Cardamom Garland", itemTamilName: "ஏலக்காய் மாலை", quantity: 1, unit: "nos", sortOrder: 3 },
    ],
    createdAt: "2026-08-01T10:10:00Z",
  },
  {
    id: "p-mrityunjaya-09",
    businessId: "biz-venkateswara-01",
    englishName: "Maha Mrityunjaya Homam",
    tamilName: "மகா மிருத்யுஞ்சய ஹோமம்",
    description: "Sacred life-saving Vedic ritual for critical health recovery, longevity and overcoming fatal doshas.",
    durationMinutes: 180,
    basePrice: 7000,
    active: true,
    items: [
      { id: "mi-1", poojaId: "p-mrityunjaya-09", itemEnglishName: "Amrita Valli Herb", itemTamilName: "சீந்தில் கொடி", quantity: 100, unit: "g", sortOrder: 1 },
      { id: "mi-2", poojaId: "p-mrityunjaya-09", itemEnglishName: "Durva Grass (Arugampul)", itemTamilName: "அருகம்புல்", quantity: 108, unit: "nos", sortOrder: 2 },
      { id: "mi-3", poojaId: "p-mrityunjaya-09", itemEnglishName: "Pure Cow Ghee", itemTamilName: "பசு நெய்", quantity: 1, unit: "litre", sortOrder: 3 },
    ],
    createdAt: "2026-08-01T10:20:00Z",
  },
  {
    id: "p-sashtiapthapoorthi-10",
    businessId: "biz-venkateswara-01",
    englishName: "Sashtiapthapoorthi (60th Kalyanam)",
    tamilName: "சஷ்டியப்தபூர்த்தி (60-ஆம் கல்யாணம்)",
    description: "Grand Vedic celebration of 60th birthday with Ayushya, Mrityunjaya, Navagraha and Mangalya Dharanam.",
    durationMinutes: 240,
    basePrice: 15000,
    active: true,
    items: [
      { id: "shi-1", poojaId: "p-sashtiapthapoorthi-10", itemEnglishName: "Mangalsutra / Thirumangalyam", itemTamilName: "திருமாங்கல்யம் கயிறு", quantity: 1, unit: "nos", sortOrder: 1 },
      { id: "shi-2", poojaId: "p-sashtiapthapoorthi-10", itemEnglishName: "64 Kalasam Pots", itemTamilName: "கலச செம்பு & தேங்காய்", quantity: 16, unit: "set", sortOrder: 2 },
      { id: "shi-3", poojaId: "p-sashtiapthapoorthi-10", itemEnglishName: "Silk Dhotis & Sarees", itemTamilName: "பட்டு வேஷ்டி & பட்டு புடவை", quantity: 2, unit: "set", sortOrder: 3 },
    ],
    createdAt: "2026-08-01T10:30:00Z",
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: "b-8248",
    bookingNumber: "#8248",
    businessId: "biz-venkateswara-01",
    customerId: "c-ramesh-01",
    customerName: "Ramesh Kumar",
    customerMobile: "+919876543210",
    customerAddress: "45, Gandhi Nagar, Namakkal",
    poojaId: "p-ganapathi-01",
    poojaEnglishName: "Ganapathi Homam",
    poojaTamilName: "கணபதி ஹோமம்",
    assignedIyerId: "m-ravi-01",
    assignedIyerName: "Ravi Iyer",
    date: "2026-09-12",
    startTime: "08:00 AM",
    endTime: "10:30 AM",
    durationMinutes: 150,
    location: "Namakkal",
    status: "COMPLETED",
    totalAmount: 5000,
    advanceAmount: 5000,
    balanceAmount: 0,
    paymentStatus: "PAID",
    notes: "Completed smoothly • Full dakshina settled",
    items: [
      { id: "bi-1", bookingId: "b-8248", itemEnglishName: "Turmeric Powder", itemTamilName: "மஞ்சள் தூள்", quantity: 100, unit: "g", isChecked: true },
      { id: "bi-2", bookingId: "b-8248", itemEnglishName: "Kumkum", itemTamilName: "குங்குமம்", quantity: 50, unit: "g", isChecked: true },
      { id: "bi-3", bookingId: "b-8248", itemEnglishName: "Betel Leaves", itemTamilName: "வெற்றிலை", quantity: 21, unit: "nos", isChecked: true },
      { id: "bi-4", bookingId: "b-8248", itemEnglishName: "Betel Nuts", itemTamilName: "பாக்கு", quantity: 21, unit: "nos", isChecked: true },
      { id: "bi-5", bookingId: "b-8248", itemEnglishName: "Banana", itemTamilName: "வாழைப்பழம்", quantity: 12, unit: "nos", isChecked: true },
      { id: "bi-6", bookingId: "b-8248", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 5, unit: "nos", isChecked: true },
    ],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-08T10:00:00Z",
    updatedAt: "2026-09-12T11:00:00Z",
  },
  {
    id: "b-8249",
    bookingNumber: "#8249",
    businessId: "biz-venkateswara-01",
    customerId: "c-meena-03",
    customerName: "Meena Sundaram",
    customerMobile: "+919032145678",
    customerAddress: "7, Fairlands, Salem",
    poojaId: "p-sathyanarayana-05",
    poojaEnglishName: "Sathyanarayana Pooja",
    poojaTamilName: "சத்தியநாராயண பூஜை",
    assignedIyerId: "m-suresh-02",
    assignedIyerName: "Suresh Iyer",
    date: "2026-09-12",
    startTime: "06:00 PM",
    endTime: "08:00 PM",
    durationMinutes: 120,
    location: "Salem",
    status: "CONFIRMED",
    totalAmount: 4500,
    advanceAmount: 1000,
    balanceAmount: 3500,
    paymentStatus: "PARTIALLY_PAID",
    notes: "Evening Pournami pooja • Advance received via GPay",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-09T14:00:00Z",
    updatedAt: "2026-09-09T14:00:00Z",
  },
  {
    id: "b-8250",
    bookingNumber: "#8250",
    businessId: "biz-venkateswara-01",
    customerId: "c-lakshmi-02",
    customerName: "Lakshmi Narayanan",
    customerMobile: "+918765432109",
    customerAddress: "18, Cross Cut Road, Coimbatore",
    poojaId: "p-navagraha-03",
    poojaEnglishName: "Navagraha Homam",
    poojaTamilName: "நவகிரக ஹோமம்",
    assignedIyerId: "m-kumar-03",
    assignedIyerName: "Kumar Iyer",
    date: "2026-09-15",
    startTime: "08:00 AM",
    endTime: "11:00 AM",
    durationMinutes: 180,
    location: "Coimbatore",
    status: "CONFIRMED",
    totalAmount: 7500,
    advanceAmount: 2000,
    balanceAmount: 5500,
    paymentStatus: "PARTIALLY_PAID",
    notes: "Planetary dosha nivarthi • Balance to collect on spot",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-10T12:00:00Z",
    updatedAt: "2026-09-10T12:00:00Z",
  },
  {
    id: "b-8251",
    bookingNumber: "#8251",
    businessId: "biz-venkateswara-01",
    customerId: "c-suresh-04",
    customerName: "Suresh Subramanian",
    customerMobile: "+919871234567",
    customerAddress: "22, Brough Road, Erode",
    poojaId: "p-gruhapravesam-04",
    poojaEnglishName: "Gruhapravesam & Vastu Homam",
    poojaTamilName: "கிரகப்பிரவேசம் & வாஸ்து ஹோமம்",
    assignedIyerId: "m-ravi-01",
    assignedIyerName: "Ravi Iyer",
    date: "2026-09-18",
    startTime: "06:00 AM",
    endTime: "10:00 AM",
    durationMinutes: 240,
    location: "Erode",
    status: "CONFIRMED",
    totalAmount: 12000,
    advanceAmount: 5000,
    balanceAmount: 7000,
    paymentStatus: "PARTIALLY_PAID",
    notes: "Brahma Muhurtham milk boiling at 6:15 AM sharp",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-11T09:00:00Z",
    updatedAt: "2026-09-11T09:00:00Z",
  },
  {
    id: "b-8252",
    bookingNumber: "#8252",
    businessId: "biz-venkateswara-01",
    customerId: "c-vignesh-05",
    customerName: "Vigneshwaran K",
    customerMobile: "+919443219876",
    customerAddress: "9, Thillai Nagar, Trichy",
    poojaId: "p-sudarshana-06",
    poojaEnglishName: "Sudarshana Homam",
    poojaTamilName: "சுதர்சன ஹோமம்",
    assignedIyerId: "m-suresh-02",
    assignedIyerName: "Suresh Iyer",
    date: "2026-09-20",
    startTime: "07:30 AM",
    endTime: "10:30 AM",
    durationMinutes: 180,
    location: "Trichy",
    status: "CONFIRMED",
    totalAmount: 8500,
    advanceAmount: 0,
    balanceAmount: 8500,
    paymentStatus: "PENDING",
    notes: "Full payment promised on ceremony day",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-12T11:00:00Z",
    updatedAt: "2026-09-12T11:00:00Z",
  },
  {
    id: "b-8253",
    bookingNumber: "#8253",
    businessId: "biz-venkateswara-01",
    customerId: "c-anandhi-06",
    customerName: "Anandhi & Senthil Nathan",
    customerMobile: "+919840123456",
    customerAddress: "14, North Mada Street, Mylapore, Chennai",
    poojaId: "p-sashtiapthapoorthi-10",
    poojaEnglishName: "Sashtiapthapoorthi (60th Kalyanam)",
    poojaTamilName: "சஷ்டியப்தபூர்த்தி (60-ஆம் கல்யாணம்)",
    assignedIyerId: "m-ravi-01",
    assignedIyerName: "Ravi Iyer",
    date: "2026-09-22",
    startTime: "09:00 AM",
    endTime: "01:00 PM",
    durationMinutes: 240,
    location: "Chennai",
    status: "CONFIRMED",
    totalAmount: 15000,
    advanceAmount: 10000,
    balanceAmount: 5000,
    paymentStatus: "PARTIALLY_PAID",
    notes: "Mylapore Kalyana Mandapam • 4 assisting Purohits",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-13T09:30:00Z",
    updatedAt: "2026-09-13T09:30:00Z",
  },
  {
    id: "b-8254",
    bookingNumber: "#8254",
    businessId: "biz-venkateswara-01",
    customerId: "c-soundar-11",
    customerName: "Soundararajan M",
    customerMobile: "+919894012345",
    customerAddress: "74, Salai Road, Dindigul",
    poojaId: "p-lakshmi-kubera-08",
    poojaEnglishName: "Maha Lakshmi Kubera Pooja",
    poojaTamilName: "மகா லக்ஷ்மி குபேர பூஜை",
    assignedIyerId: "m-kumar-03",
    assignedIyerName: "Kumar Iyer",
    date: "2026-09-25",
    startTime: "06:00 PM",
    endTime: "07:30 PM",
    durationMinutes: 90,
    location: "Dindigul",
    status: "CONFIRMED",
    totalAmount: 4500,
    advanceAmount: 4500,
    balanceAmount: 0,
    paymentStatus: "PAID",
    notes: "Paid in full in advance via UPI",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-14T15:00:00Z",
    updatedAt: "2026-09-14T15:00:00Z",
  },
  {
    id: "b-8255",
    bookingNumber: "#8255",
    businessId: "biz-venkateswara-01",
    customerId: "c-balaji-07",
    customerName: "Dr. Balaji Raghavan",
    customerMobile: "+919443156789",
    customerAddress: "52, KK Nagar, Madurai",
    poojaId: "p-rudra-07",
    poojaEnglishName: "Sri Rudra Ekadasa Homam",
    poojaTamilName: "ஸ்ரீ ருத்ர ஏகாதச ஹோமம்",
    assignedIyerId: "m-venkatesh-04",
    assignedIyerName: "Venkatesh Iyer",
    date: "2026-09-28",
    startTime: "07:00 AM",
    endTime: "10:30 AM",
    durationMinutes: 210,
    location: "Madurai",
    status: "CONFIRMED",
    totalAmount: 9000,
    advanceAmount: 3000,
    balanceAmount: 6000,
    paymentStatus: "PARTIALLY_PAID",
    notes: "Clinic anniversary homam & health sankalpam",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-15T10:00:00Z",
    updatedAt: "2026-09-15T10:00:00Z",
  },
  {
    id: "b-8256",
    bookingNumber: "#8256",
    businessId: "biz-venkateswara-01",
    customerId: "c-karthik-08",
    customerName: "Karthikeyan Ramaswamy",
    customerMobile: "+919789012345",
    customerAddress: "88, High Ground, Tirunelveli",
    poojaId: "p-mrityunjaya-09",
    poojaEnglishName: "Maha Mrityunjaya Homam",
    poojaTamilName: "மகா மிருத்யுஞ்சய ஹோமம்",
    assignedIyerId: "m-suresh-02",
    assignedIyerName: "Suresh Iyer",
    date: "2026-10-02",
    startTime: "08:00 AM",
    endTime: "11:00 AM",
    durationMinutes: 180,
    location: "Tirunelveli",
    status: "CONFIRMED",
    totalAmount: 7000,
    advanceAmount: 0,
    balanceAmount: 7000,
    paymentStatus: "PENDING",
    notes: "Gandhi Jayanthi holiday booking",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-15T16:00:00Z",
    updatedAt: "2026-09-15T16:00:00Z",
  },
  {
    id: "b-8257",
    bookingNumber: "#8257",
    businessId: "biz-venkateswara-01",
    customerId: "c-revathi-12",
    customerName: "Revathi Krishnan",
    customerMobile: "+919790123456",
    customerAddress: "25, Katpadi Road, Vellore",
    poojaId: "p-ayushya-02",
    poojaEnglishName: "Ayushya Homam",
    poojaTamilName: "ஆயுஷ்ய ஹோமம்",
    assignedIyerId: "m-kumar-03",
    assignedIyerName: "Kumar Iyer",
    date: "2026-10-05",
    startTime: "09:00 AM",
    endTime: "12:00 PM",
    durationMinutes: 180,
    location: "Vellore",
    status: "CONFIRMED",
    totalAmount: 6000,
    advanceAmount: 2000,
    balanceAmount: 4000,
    paymentStatus: "PARTIALLY_PAID",
    notes: "1st Birthday of grandson • Ayush Sukta Javam",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-16T08:00:00Z",
    updatedAt: "2026-09-16T08:00:00Z",
  },
  {
    id: "b-8258",
    bookingNumber: "#8258",
    businessId: "biz-venkateswara-01",
    customerId: "c-lakshmi-02",
    customerName: "Lakshmi Narayanan",
    customerMobile: "+918765432109",
    customerAddress: "18, Cross Cut Road, Coimbatore",
    poojaId: "p-durga-11",
    poojaEnglishName: "Durga Pooja",
    poojaTamilName: "துர்கா பூஜை",
    assignedIyerId: "m-ravi-01",
    assignedIyerName: "Ravi Iyer",
    date: "2026-10-14",
    startTime: "06:00 PM",
    endTime: "08:00 PM",
    durationMinutes: 120,
    location: "Coimbatore",
    status: "CONFIRMED",
    totalAmount: 5500,
    advanceAmount: 2000,
    balanceAmount: 3500,
    paymentStatus: "PARTIALLY_PAID",
    notes: "Navarathri Special Durga Pooja",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-16T09:00:00Z",
    updatedAt: "2026-09-16T09:00:00Z",
  },
  {
    id: "b-8259",
    bookingNumber: "#8259",
    businessId: "biz-venkateswara-01",
    customerId: "c-meena-03",
    customerName: "Meena Sundaram",
    customerMobile: "+919032145678",
    customerAddress: "7, Fairlands, Salem",
    poojaId: "p-sathyanarayana-05",
    poojaEnglishName: "Satyanarayana Pooja",
    poojaTamilName: "சத்தியநாராயண பூஜை",
    assignedIyerId: "m-suresh-02",
    assignedIyerName: "Suresh Iyer",
    date: "2026-10-23",
    startTime: "09:00 AM",
    endTime: "11:30 AM",
    durationMinutes: 150,
    location: "Salem",
    status: "CONFIRMED",
    totalAmount: 5000,
    advanceAmount: 5000,
    balanceAmount: 0,
    paymentStatus: "PAID",
    notes: "Aipasi Pournami Vratha Pooja",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-16T10:00:00Z",
    updatedAt: "2026-09-16T10:00:00Z",
  },
  {
    id: "b-8260",
    bookingNumber: "#8260",
    businessId: "biz-venkateswara-01",
    customerId: "c-ramesh-01",
    customerName: "Ramesh Kumar",
    customerMobile: "+919876543210",
    customerAddress: "45, Gandhi Nagar, Namakkal",
    poojaId: "p-karthigai-12",
    poojaEnglishName: "Karthigai Deepam Pooja",
    poojaTamilName: "கார்த்திகை தீபம் பூஜை",
    assignedIyerId: "m-ravi-01",
    assignedIyerName: "Ravi Iyer",
    date: "2026-11-08",
    startTime: "06:00 PM",
    endTime: "08:00 PM",
    durationMinutes: 120,
    location: "Namakkal",
    status: "CONFIRMED",
    totalAmount: 4000,
    advanceAmount: 2000,
    balanceAmount: 2000,
    paymentStatus: "PARTIALLY_PAID",
    notes: "Karthigai Deepam lamp lighting & special archana",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-16T11:00:00Z",
    updatedAt: "2026-09-16T11:00:00Z",
  },
  {
    id: "b-8261",
    bookingNumber: "#8261",
    businessId: "biz-venkateswara-01",
    customerId: "c-vignesh-05",
    customerName: "Vigneshwaran K",
    customerMobile: "+919443219876",
    customerAddress: "9, Thillai Nagar, Trichy",
    poojaId: "p-subamuhurtha-13",
    poojaEnglishName: "Subamuhurtha Pooja",
    poojaTamilName: "சுபமுகூர்த்த பூஜை",
    assignedIyerId: "m-kumar-03",
    assignedIyerName: "Kumar Iyer",
    date: "2026-11-21",
    startTime: "09:00 AM",
    endTime: "11:00 AM",
    durationMinutes: 120,
    location: "Trichy",
    status: "CONFIRMED",
    totalAmount: 6500,
    advanceAmount: 6500,
    balanceAmount: 0,
    paymentStatus: "PAID",
    notes: "Auspicious wedding muhurtham sankalpam",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-16T12:00:00Z",
    updatedAt: "2026-09-16T12:00:00Z",
  },
];
