import { User, Business, BusinessMember, Subscription, Customer, Pooja, Booking } from "@/lib/types";

export const SEED_USER: User = {
  id: "u-ravi-iyer-01",
  googleId: "google-1092837465",
  email: "ravi.iyer@gmail.com",
  name: "Ravi Iyer",
  avatarUrl: "",
  mobile: "+919876543210",
  mobileVerified: true,
  role: "OWNER",
  referralCode: "VELVI-RAVI123",
  createdAt: "2026-08-01T08:00:00Z",
};

export const SEED_SUPER_ADMIN: User = {
  id: "u-super-admin-01",
  googleId: "google-admin-9999",
  email: "admin@velvi.app",
  name: "Velvi Admin",
  avatarUrl: "",
  mobile: "+919999999999",
  mobileVerified: true,
  role: "SUPER_ADMIN",
  referralCode: "VELVI-ADMIN",
  createdAt: "2026-01-01T00:00:00Z",
};

export const SEED_BUSINESS: Business = {
  id: "biz-venkateswara-01",
  ownerId: "u-ravi-iyer-01",
  name: "",
  iyerName: "",
  logoUrl: "",
  phone: "+919876543210",
  whatsapp: "",
  address: "",
  showWatermark: true,
  createdAt: "2026-08-01T08:30:00Z",
};

export const SEED_SUBSCRIPTION: Subscription = {
  id: "sub-ravi-01",
  businessId: "biz-venkateswara-01",
  planName: "Velvi Pro",
  planCode: "VELVI_PRO",
  status: "ACTIVE",
  trialStart: "2026-08-01T08:30:00Z",
  trialEnd: "2026-08-31T08:30:00Z",
  currentPeriodStart: "2026-08-31T08:30:00Z",
  currentPeriodEnd: "2026-10-18T23:59:59Z", // Matches mockup: "Valid until 18 Oct 2026"
  billingCycle: "MONTHLY",
  autoRenew: true,
  createdAt: "2026-08-01T08:30:00Z",
  updatedAt: "2026-08-31T08:30:00Z",
};

export const SEED_MEMBERS: BusinessMember[] = [
  {
    id: "m-ravi-01",
    businessId: "biz-venkateswara-01",
    userId: "u-ravi-iyer-01",
    name: "Ravi Iyer",
    mobile: "+919876543210",
    role: "OWNER",
    active: true,
    specialization: "Ganapathi, Ayushya & Gruhapravesam",
    workingDays: "All days",
    workingHours: "06:00 - 20:00",
    bookingCount: 12,
    createdAt: "2026-08-01T08:30:00Z",
  },
  {
    id: "m-suresh-02",
    businessId: "biz-venkateswara-01",
    userId: "u-suresh-iyer-02",
    name: "Suresh Iyer",
    mobile: "+919876543211",
    role: "IYER",
    active: true,
    specialization: "Navagraha & Sudarshana Homam",
    workingDays: "All days",
    workingHours: "06:00 - 21:00",
    bookingCount: 8,
    createdAt: "2026-08-05T10:00:00Z",
  },
  {
    id: "m-kumar-03",
    businessId: "biz-venkateswara-01",
    userId: "u-kumar-iyer-03",
    name: "Kumar Iyer",
    mobile: "+919876543212",
    role: "IYER",
    active: true,
    specialization: "Sathyanarayana Pooja & Seemantham",
    workingDays: "Mon-Sat",
    workingHours: "07:00 - 18:00",
    bookingCount: 10,
    createdAt: "2026-08-10T11:00:00Z",
  },
  {
    id: "m-venkatesh-04",
    businessId: "biz-venkateswara-01",
    userId: "u-venkatesh-04",
    name: "Venkatesh Iyer",
    mobile: "+919876543213",
    role: "IYER",
    active: false,
    specialization: "Mrityunjaya & Lakshmi Homam",
    workingDays: "Weekends only",
    workingHours: "06:00 - 14:00",
    bookingCount: 3,
    createdAt: "2026-08-15T09:00:00Z",
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: "c-ramesh-01",
    businessId: "biz-venkateswara-01",
    name: "Ramesh Kumar",
    mobile: "+919876543210",
    whatsapp: "+919876543210",
    address: "45, Gandhi Nagar, Namakkal",
    city: "Namakkal",
    notes: "Family priest for 6 years",
    createdAt: "2026-08-12T10:00:00Z",
  },
  {
    id: "c-lakshmi-02",
    businessId: "biz-venkateswara-01",
    name: "Lakshmi Narayanan",
    mobile: "+918765432109",
    whatsapp: "+918765432109",
    address: "18, Cross Cut Road, Coimbatore",
    city: "Coimbatore",
    notes: "Requires Tamil Panchangam muhurtham notes",
    createdAt: "2026-08-20T14:00:00Z",
  },
  {
    id: "c-meena-03",
    businessId: "biz-venkateswara-01",
    name: "Meena",
    mobile: "+919032145678",
    whatsapp: "+919032145678",
    address: "7, Fairlands, Salem",
    city: "Salem",
    notes: "Regular Navaratri / Varalakshmi bookings",
    createdAt: "2026-08-25T16:00:00Z",
  },
  {
    id: "c-suresh-04",
    businessId: "biz-venkateswara-01",
    name: "Suresh",
    mobile: "+919871234567",
    whatsapp: "+919871234567",
    address: "22, Brough Road, Erode",
    city: "Erode",
    notes: "Gruhapravesam upcoming next month",
    createdAt: "2026-09-01T11:00:00Z",
  },
  {
    id: "c-vignesh-05",
    businessId: "biz-venkateswara-01",
    name: "Vignesh",
    mobile: "+919443219876",
    whatsapp: "+919443219876",
    address: "9, Thillai Nagar, Trichy",
    city: "Trichy",
    notes: "Referred by Ramesh Kumar",
    createdAt: "2026-09-02T12:00:00Z",
  },
];

export const SEED_POOJAS: Pooja[] = [
  {
    id: "p-ganapathi-01",
    businessId: "biz-venkateswara-01",
    englishName: "Ganapathi Homam",
    tamilName: "கணபதி ஹோமம்",
    description: "Invokes Lord Ganesha to remove all obstacles, grant success, health and prosperity before new ventures.",
    durationMinutes: 150,
    basePrice: 5000,
    procedure: "Sankalpam, Ganapathi Avahanam, Shodashopachara Pooja, 108 Ashtothram, Ganapathi Moola Mantra Homam, Poornahuthi, Aashirvadam.",
    active: true,
    items: [
      { id: "gi-1", poojaId: "p-ganapathi-01", itemEnglishName: "Turmeric Powder", itemTamilName: "மஞ்சள் தூள்", quantity: 100, unit: "g", sortOrder: 1 },
      { id: "gi-2", poojaId: "p-ganapathi-01", itemEnglishName: "Kumkum", itemTamilName: "குங்குமம்", quantity: 50, unit: "g", sortOrder: 2 },
      { id: "gi-3", poojaId: "p-ganapathi-01", itemEnglishName: "Betel Leaves", itemTamilName: "வெற்றிலை", quantity: 21, unit: "nos", sortOrder: 3 },
      { id: "gi-4", poojaId: "p-ganapathi-01", itemEnglishName: "Betel Nuts", itemTamilName: "பாக்கு", quantity: 21, unit: "nos", sortOrder: 4 },
      { id: "gi-5", poojaId: "p-ganapathi-01", itemEnglishName: "Banana", itemTamilName: "வாழைப்பழம்", quantity: 12, unit: "nos", sortOrder: 5 },
      { id: "gi-6", poojaId: "p-ganapathi-01", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 5, unit: "nos", sortOrder: 6 },
      { id: "gi-7", poojaId: "p-ganapathi-01", itemEnglishName: "Raw Rice", itemTamilName: "பச்சரிசி", quantity: 2, unit: "kg", sortOrder: 7 },
      { id: "gi-8", poojaId: "p-ganapathi-01", itemEnglishName: "Navadhanyam", itemTamilName: "நவதானியம்", quantity: 1, unit: "set", sortOrder: 8 },
      { id: "gi-9", poojaId: "p-ganapathi-01", itemEnglishName: "Samithu Bundle", itemTamilName: "சமித்துக் கட்டு", quantity: 1, unit: "bundle", sortOrder: 9 },
      { id: "gi-10", poojaId: "p-ganapathi-01", itemEnglishName: "Pure Ghee", itemTamilName: "தூய பசு நெய்", quantity: 500, unit: "ml", sortOrder: 10 },
      { id: "gi-11", poojaId: "p-ganapathi-01", itemEnglishName: "Flowers & Garlands", itemTamilName: "பூ மாலை & உதிரிப்பூ", quantity: 500, unit: "g", sortOrder: 11 },
      { id: "gi-12", poojaId: "p-ganapathi-01", itemEnglishName: "Jaggery (Vellam)", itemTamilName: "வெல்லம்", quantity: 500, unit: "g", sortOrder: 12 },
      { id: "gi-13", poojaId: "p-ganapathi-01", itemEnglishName: "Dry Fruits & Nuts", itemTamilName: "உலர்ந்த திராட்சை & முந்திரி", quantity: 100, unit: "g", sortOrder: 13 },
      { id: "gi-14", poojaId: "p-ganapathi-01", itemEnglishName: "Modakam / Prasadam", itemTamilName: "மோதகம் நைவேத்தியம்", quantity: 21, unit: "nos", sortOrder: 14 },
    ],
    createdAt: "2026-08-01T09:00:00Z",
  },
  {
    id: "p-ayushya-02",
    businessId: "biz-venkateswara-01",
    englishName: "Ayushya Homam",
    tamilName: "ஆயுஷ்ய ஹோமம்",
    description: "Performed on birthdays or milestones to grant longevity, good health, and vitality for child or elder.",
    durationMinutes: 180,
    basePrice: 6000,
    active: true,
    items: [
      { id: "ai-1", poojaId: "p-ayushya-02", itemEnglishName: "Turmeric Powder", itemTamilName: "மஞ்சள் தூள்", quantity: 100, unit: "g", sortOrder: 1 },
      { id: "ai-2", poojaId: "p-ayushya-02", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 6, unit: "nos", sortOrder: 2 },
      { id: "ai-3", poojaId: "p-ayushya-02", itemEnglishName: "Ghee", itemTamilName: "பசு நெய்", quantity: 1, unit: "litre", sortOrder: 3 },
      { id: "ai-4", poojaId: "p-ayushya-02", itemEnglishName: "Samithu Bundle", itemTamilName: "சமித்துக் கட்டு", quantity: 2, unit: "bundle", sortOrder: 4 },
      { id: "ai-5", poojaId: "p-ayushya-02", itemEnglishName: "Charu Patram / Rice", itemTamilName: "சாரு நைவேத்திய பச்சரிசி", quantity: 2, unit: "kg", sortOrder: 5 },
    ],
    createdAt: "2026-08-01T09:10:00Z",
  },
  {
    id: "p-navagraha-03",
    businessId: "biz-venkateswara-01",
    englishName: "Navagraha Homam",
    tamilName: "நவகிரக ஹோமம்",
    description: "Pacifies planetary doshas and brings peace, stability, family harmony, and planetary blessings.",
    durationMinutes: 180,
    basePrice: 7500,
    active: true,
    items: [
      { id: "ni-1", poojaId: "p-navagraha-03", itemEnglishName: "Navadhanyam Set", itemTamilName: "நவதானியம் 9 வகை", quantity: 1, unit: "set", sortOrder: 1 },
      { id: "ni-2", poojaId: "p-navagraha-03", itemEnglishName: "9 Color Vastram", itemTamilName: "9 வண்ண வஸ்திரம்", quantity: 1, unit: "set", sortOrder: 2 },
      { id: "ni-3", poojaId: "p-navagraha-03", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 9, unit: "nos", sortOrder: 3 },
      { id: "ni-4", poojaId: "p-navagraha-03", itemEnglishName: "Ghee", itemTamilName: "பசு நெய்", quantity: 1, unit: "litre", sortOrder: 4 },
    ],
    createdAt: "2026-08-01T09:20:00Z",
  },
  {
    id: "p-gruhapravesam-04",
    businessId: "biz-venkateswara-01",
    englishName: "Gruhapravesam",
    tamilName: "கிரகப்பிரவேசம்",
    description: "New house warming ceremony, Vastu Homam, Navagraha and Ganapathi pooja for auspicious living.",
    durationMinutes: 240,
    basePrice: 12000,
    active: true,
    items: [
      { id: "gi-101", poojaId: "p-gruhapravesam-04", itemEnglishName: "Gomatha Pooja Set", itemTamilName: "கோ பூஜை பொருட்கள்", quantity: 1, unit: "set", sortOrder: 1 },
      { id: "gi-102", poojaId: "p-gruhapravesam-04", itemEnglishName: "Milk & Pot for Boiling", itemTamilName: "பால் காய்ச்சும் பாத்திரம் & பால்", quantity: 2, unit: "litre", sortOrder: 2 },
      { id: "gi-103", poojaId: "p-gruhapravesam-04", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 11, unit: "nos", sortOrder: 3 },
      { id: "gi-104", poojaId: "p-gruhapravesam-04", itemEnglishName: "Vastu Yantram", itemTamilName: "வாஸ்து எந்திரம்", quantity: 1, unit: "nos", sortOrder: 4 },
    ],
    createdAt: "2026-08-01T09:30:00Z",
  },
  {
    id: "p-sathyanarayana-05",
    businessId: "biz-venkateswara-01",
    englishName: "Sathyanarayana Pooja",
    tamilName: "சத்தியநாராயண பூஜை",
    description: "Traditional auspicious Vratham for blessings, wish fulfillment, and family prosperity on Pournami.",
    durationMinutes: 120,
    basePrice: 4500,
    active: true,
    items: [
      { id: "si-1", poojaId: "p-sathyanarayana-05", itemEnglishName: "Sathyanarayana Photo/Idol", itemTamilName: "ஸ்ரீ சத்தியநாராயணர் படம்", quantity: 1, unit: "nos", sortOrder: 1 },
      { id: "si-2", poojaId: "p-sathyanarayana-05", itemEnglishName: "Sooji & Sugar for Sheera", itemTamilName: "ரவை & சர்க்கரை ஷீரா பிரசாதம்", quantity: 1, unit: "kg", sortOrder: 2 },
      { id: "si-3", poojaId: "p-sathyanarayana-05", itemEnglishName: "Tulasi Leaves", itemTamilName: "துளசி தளம்", quantity: 100, unit: "g", sortOrder: 3 },
      { id: "si-4", poojaId: "p-sathyanarayana-05", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 5, unit: "nos", sortOrder: 4 },
    ],
    createdAt: "2026-08-01T09:40:00Z",
  },
  {
    id: "p-sudarshana-06",
    businessId: "biz-venkateswara-01",
    englishName: "Sudarshana Homam",
    tamilName: "சுதர்சன ஹோமம்",
    description: "Invokes Lord Sudarshana Chakra for absolute protection from negative energy, enemies and evil eyes.",
    durationMinutes: 180,
    basePrice: 8500,
    active: true,
    items: [
      { id: "sui-1", poojaId: "p-sudarshana-06", itemEnglishName: "White Mustard Seeds", itemTamilName: "வெண்கடுகு", quantity: 250, unit: "g", sortOrder: 1 },
      { id: "sui-2", poojaId: "p-sudarshana-06", itemEnglishName: "Pure Ghee", itemTamilName: "பசு நெய்", quantity: 1, unit: "litre", sortOrder: 2 },
    ],
    createdAt: "2026-08-01T09:50:00Z",
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: "b-8248",
    bookingNumber: "#8248",
    businessId: "biz-venkateswara-01",
    customerId: "c-ramesh-01",
    customerName: "Ramesh Kumar",
    customerMobile: "+919876543210",
    customerAddress: "Namakkal",
    poojaId: "p-ganapathi-01",
    poojaEnglishName: "Ganapathi Homam",
    poojaTamilName: "கணபதி ஹோமம்",
    assignedIyerId: "m-ravi-01",
    assignedIyerName: "Ravi Iyer",
    date: "2026-09-12",
    startTime: "08:00 AM",
    endTime: "10:30 AM",
    durationMinutes: 150,
    location: "Namakkal",
    status: "CONFIRMED",
    totalAmount: 5000,
    advanceAmount: 5000,
    balanceAmount: 0,
    paymentStatus: "PAID",
    notes: "Muhurtham starts sharp at 8:15 AM",
    items: [
      { id: "bi-1", bookingId: "b-8248", itemEnglishName: "Turmeric Powder", itemTamilName: "மஞ்சள் தூள்", quantity: 100, unit: "g", isChecked: true },
      { id: "bi-2", bookingId: "b-8248", itemEnglishName: "Kumkum", itemTamilName: "குங்குமம்", quantity: 50, unit: "g", isChecked: true },
      { id: "bi-3", bookingId: "b-8248", itemEnglishName: "Betel Leaves", itemTamilName: "வெற்றிலை", quantity: 21, unit: "nos", isChecked: true },
      { id: "bi-4", bookingId: "b-8248", itemEnglishName: "Betel Nuts", itemTamilName: "பாக்கு", quantity: 21, unit: "nos", isChecked: true },
      { id: "bi-5", bookingId: "b-8248", itemEnglishName: "Banana", itemTamilName: "வாழைப்பழம்", quantity: 12, unit: "nos", isChecked: false },
      { id: "bi-6", bookingId: "b-8248", itemEnglishName: "Coconuts", itemTamilName: "தேங்காய்", quantity: 5, unit: "nos", isChecked: false },
    ],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-08T10:00:00Z",
    updatedAt: "2026-09-08T10:00:00Z",
  },
  {
    id: "b-8249",
    bookingNumber: "#8249",
    businessId: "biz-venkateswara-01",
    customerId: "c-meena-03",
    customerName: "Kumar / Meena",
    customerMobile: "+919032145678",
    customerAddress: "Fairlands, Salem",
    poojaId: "p-sathyanarayana-05",
    poojaEnglishName: "Sathyanarayana Pooja",
    poojaTamilName: "சத்தியநாராயண பூஜை",
    assignedIyerId: "m-suresh-02",
    assignedIyerName: "Suresh Iyer",
    date: "2026-09-12",
    startTime: "06:00 PM",
    endTime: "08:00 PM",
    durationMinutes: 120,
    location: "Salem",
    status: "CONFIRMED",
    totalAmount: 4500,
    advanceAmount: 1000,
    balanceAmount: 3500,
    paymentStatus: "PARTIALLY_PAID",
    notes: "Evening Pournami pooja",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-09T14:00:00Z",
    updatedAt: "2026-09-09T14:00:00Z",
  },
  {
    id: "b-8250",
    bookingNumber: "#8250",
    businessId: "biz-venkateswara-01",
    customerId: "c-lakshmi-02",
    customerName: "Lakshmi Narayanan",
    customerMobile: "+918765432109",
    customerAddress: "Cross Cut Road, Coimbatore",
    poojaId: "p-navagraha-03",
    poojaEnglishName: "Navagraha Homam",
    poojaTamilName: "நவகிரக ஹோமம்",
    assignedIyerId: "m-kumar-03",
    assignedIyerName: "Kumar Iyer",
    date: "2026-09-15",
    startTime: "08:00 AM",
    endTime: "11:00 AM",
    durationMinutes: 180,
    location: "Coimbatore",
    status: "CONFIRMED",
    totalAmount: 7500,
    advanceAmount: 0,
    balanceAmount: 7500,
    paymentStatus: "PENDING",
    notes: "Planetary dosha nivarthi",
    items: [],
    createdBy: "u-ravi-iyer-01",
    createdAt: "2026-09-10T12:00:00Z",
    updatedAt: "2026-09-10T12:00:00Z",
  },
];
